/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BusinessLayer.Componente;
import BusinessLayer.ConfiguraFacil;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;

public class MA_AtualizarStock  extends JFrame {

    private ConfiguraFacil cfacil;
    private Componente c; 
    /**
     * Creates new form Atualizar_Stock
     */
    public MA_AtualizarStock(ConfiguraFacil cfacil, int idComponente, int stock) {
        initComponents();
        this.cfacil = cfacil;
        this.c = this.cfacil.getComponente(idComponente);
        
        qtAtual.setText(Integer.toString(c.getStock()));
        qtAtual.setEditable(false);
        descricao.setText(c.getDesignacaoComp());
        descricao.setEditable(false);
        qtRecebida.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtAtual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qtRecebida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        atualizar_Button = new javax.swing.JButton();
        cancelar_Button = new javax.swing.JButton();
        descricao = new javax.swing.JTextField();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 250));

        jLabel1.setText("Descrição do artigo:");

        jLabel2.setText("Quantidade Atual:");

        jLabel3.setText("Quantidade Recebida: ");

        qtRecebida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtRecebidaKeyReleased(evt);
            }
        });

        jLabel4.setText("Total: ");

        atualizar_Button.setText("Atualizar");
        atualizar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_ButtonActionPerformed(evt);
            }
        });

        cancelar_Button.setText("Cancelar");
        cancelar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(atualizar_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtRecebida)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelar_Button)
                                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 5, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(qtAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(qtRecebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atualizar_Button)
                            .addComponent(cancelar_Button)))
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validaDados() 
    {
        boolean vazio = this.qtRecebida.getText().equals("");
        
        if (vazio)
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos.", "Formulário incompleto", 0);
        
        return !vazio;
    }
    
    private void atualizar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar_ButtonActionPerformed
        
        String total;
        int novoStock;
        
        if (this.validaDados()) {
            novoStock = this.c.getStock()+Integer.parseInt(this.qtRecebida.getText());
            this.cfacil.atualizaStock(this.c.getIdComponente(), novoStock);        
        }
        this.dispose();
        
    }//GEN-LAST:event_atualizar_ButtonActionPerformed
    
    private void cancelar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_ButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelar_ButtonActionPerformed

    private void qtRecebidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtRecebidaKeyReleased
        String qt = this.qtRecebida.getText();
        if(qt.equals(""))
            total.setText(Integer.toString(this.c.getStock()));
        else
            total.setText(Integer.toString(this.c.getStock()+Integer.parseInt(qt)));
    }//GEN-LAST:event_qtRecebidaKeyReleased

   
    public void update(Observable observable, Object obj) {
        int res = this.c.getStock()+Integer.parseInt(this.qtRecebida.getText());
        
        this.total.setText(""+res);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar_Button;
    private javax.swing.JButton cancelar_Button;
    private javax.swing.JTextField descricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField qtAtual;
    private javax.swing.JTextField qtRecebida;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
