/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BusinessLayer.Componente;
import BusinessLayer.ConfiguraFacil;
import javax.swing.table.DefaultTableModel;


public class MV_AlteracoesConfig extends javax.swing.JFrame {

    private MV_ConfigIndividualizada cIndividualizada;
    private ConfiguraFacil cfacil;
    private MV_NifCliente nifCliente;
    /**
     * Creates new form AlteracoesConfig
     */
    public MV_AlteracoesConfig(MV_ConfigIndividualizada cIndividualizada) {
        initComponents();
        this.cIndividualizada = cIndividualizada;
        this.cfacil = cIndividualizada.getCFacil();
        updateTableCompRemover();
        updateTableCompInserir();
        updateTablePacksRemover();
        updateTablePacksInserir();
    }
   
    
    private void updateTableCompRemover() {
        
        DefaultTableModel model = (DefaultTableModel) compRemover.getModel();
        
        model.setRowCount(0);
        
        for(int i: cfacil.getComponentesRemover()) {
            
            Object rowData[] = new Object[3];
            rowData[0] = cfacil.getComponentes().get(i).getIdComponente();
            rowData[1] = cfacil.getComponentes().get(i).getDesignacaoComp();
            rowData[2] = cfacil.valorPagarComponente(i);
            model.addRow(rowData); 
        }
    }
    
    private void updateTableCompInserir() {
        
        DefaultTableModel model = (DefaultTableModel) compInserir.getModel();
        
        model.setRowCount(0);
        for(int i: cfacil.getComponentesInserir()) {
            Object rowData[] = new Object[3];
            rowData[0] = cfacil.getComponentes().get(i).getIdComponente();
            rowData[1] = cfacil.getComponentes().get(i).getDesignacaoComp();
            rowData[2] = cfacil.valorPagarComponente(i);
            model.addRow(rowData); 
        }
    }
    
    private void updateTablePacksRemover() {
        
        DefaultTableModel model = (DefaultTableModel) packRemover.getModel();
        
        model.setRowCount(0);
        for(int i: cfacil.getPacksRemover()) {
            Object rowData[] = new Object[3];
            rowData[0] = cfacil.getPacotes().get(i).getIdPack();
            rowData[1] = cfacil.getPacotes().get(i).getDesignacaoPack();
            rowData[2] = cfacil.getPacotes().get(i).getPrecoPack();
            model.addRow(rowData); 
        }
    }
    
    private void updateTablePacksInserir() {
        
        DefaultTableModel model = (DefaultTableModel) packInserir.getModel();
        
        model.setRowCount(0);
        for(int i: cfacil.getPacksInserir()) {
            Object rowData[] = new Object[3];
            rowData[0] = cfacil.getPacotes().get(i).getIdPack();
            rowData[1] = cfacil.getPacotes().get(i).getDesignacaoPack();
            rowData[2] = cfacil.getPacotes().get(i).getPrecoPack();
            model.addRow(rowData); 
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        compRemover = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        packRemover = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        compInserir = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        packInserir = new javax.swing.JTable();
        aceitar = new javax.swing.JButton();
        ignorar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("A opção selecionada exige alterações na configuração.");

        compRemover.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Designação", "Preço"
            }
        ));
        jScrollPane1.setViewportView(compRemover);

        jLabel2.setText("Componentes a remover:");

        jLabel3.setText("Packs a remover:");

        packRemover.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Designação", "Preço"
            }
        ));
        jScrollPane2.setViewportView(packRemover);

        jLabel4.setText("Componentes a inserir:");

        compInserir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Designaçao", "Preço"
            }
        ));
        jScrollPane3.setViewportView(compInserir);

        packInserir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Designação", "Preço"
            }
        ));
        jScrollPane4.setViewportView(packInserir);

        aceitar.setText("Aceitar Alterações");
        aceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceitarActionPerformed(evt);
            }
        });

        ignorar.setText("Ignorar Alterações");
        ignorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignorarActionPerformed(evt);
            }
        });

        jLabel5.setText("Packs a inserir:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(aceitar)
                        .addGap(18, 18, 18)
                        .addComponent(ignorar)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceitar)
                    .addComponent(ignorar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceitarActionPerformed
        this.cfacil.atualizaListaComp();
        this.cfacil.atualizaListaPacks();
        this.cIndividualizada.carregaEstado();
        this.dispose();    
    }//GEN-LAST:event_aceitarActionPerformed

    private void ignorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignorarActionPerformed
        this.cIndividualizada.carregaEstado();
        this.dispose();
    }//GEN-LAST:event_ignorarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceitar;
    private javax.swing.JTable compInserir;
    private javax.swing.JTable compRemover;
    private javax.swing.JButton ignorar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable packInserir;
    private javax.swing.JTable packRemover;
    // End of variables declaration//GEN-END:variables
}
