/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BusinessLayer.ConfiguraFacil;


public class MV_MenuVendedor extends javax.swing.JFrame {

    private ConfiguraFacil cfacil;
    private MV_ConfigIndividualizada ci;
    private ConfigOtima co;
    private Login login;
    /**
     * Creates new form Menu_Vendedor
     */
    public MV_MenuVendedor(ConfiguraFacil cfacil) {
        initComponents();
        this.cfacil=cfacil; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfigOtm_Button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ConfigInd_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConfigOtm_Button.setText("Configuração Otima");
        ConfigOtm_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigOtm_ButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ConfigInd_Button.setText("Configuração Individualizada");
        ConfigInd_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigInd_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConfigOtm_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfigInd_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addComponent(ConfigInd_Button)
                .addGap(18, 18, 18)
                .addComponent(ConfigOtm_Button)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfigInd_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigInd_ButtonActionPerformed
        cfacil.iniciaConfig();
        ci = new MV_ConfigIndividualizada(cfacil);
        ci.setTitle("Configuração Individualizada");
        ci.setVisible(true);
    }//GEN-LAST:event_ConfigInd_ButtonActionPerformed

    private void ConfigOtm_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigOtm_ButtonActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Esta opção encontra-se em fase de desenvolvimento!", "Em construção!", 0);
        //co = new ConfigOtima(cfacil);
        //co.setTitle("Configuração Otima");
        //co.setVisible(true);
    }//GEN-LAST:event_ConfigOtm_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        login = new Login();
        login.setTitle("Login");
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfigInd_Button;
    private javax.swing.JButton ConfigOtm_Button;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
